site:
    testingOnly: false
    name: Synopackage.com
    theme: classic
    latestVersion: 6.2-23739
    defaultModel: DS418play
    websiteVersion: 1.0.8
    useCache: true
    #in strtotime format
    cacheExpiration: -1 day
    cachePngExpiration: -30 days
    logExecutionTime: true
    logSearchQueries: true
    newsPerPage: 5
    #curl options:
    #in seconds
    curlTimeout: 15
    #leave empty if no proxy
    curlProxy:
    #google analytics code (leave empty if not used)
    googleStatisticsCode: 
    donateUrls:
        - entry: 
            subsystem: paypal
            url: https://paypal.me/pools/c/7Z6MxYfUWn
            isPaypal: true
    
# ALL PATHS MUST BE RELATIVE TO THE ROOT
# DIRECTORY (where the index.php is located)
# INCLUDE TRAILING SLASH FOR DIRECTORIES!
paths:
    cache: cache/
    sourceUrls: conf/source_urls.yaml
    models: conf/synology_models.yaml
    versions: conf/DSMVersions.yaml
    changelog: conf/changelog.yaml
    news: conf/news.yaml
    faq: conf/faq.yaml
    monologDebug: logs/debug.log
    monologError: logs/error.log
relativePaths:
    themes: themes/
    cache: cache/
